DROP TABLE IF EXISTS CONNECTIONS;
CREATE TABLE CONNECTIONS( ID_CONNECTION INT PRIMARY KEY AUTO_INCREMENT, SRC_IP VARCHAR(45) NOT NULL, URI VARCHAR(45) NOT NULL, TIME_STAMP DECIMAL NOT NULL,  SEND_B DECIMAL NOT NULL, RECEIVED_B DECIMAL NOT NULL, SPEED DECIMAL NOT NULL);
INSERT INTO CONNECTIONS (SRC_IP, URI, TIME_STAMP, SEND_B, RECEIVED_B, SPEED)  VALUES ('111.11.11.11', '/hello', '1000000', '1111', '1111', '1000');
SELECT * FROM CONNECTIONS;