DROP TABLE IF EXISTS REDIRECTS;
CREATE TABLE REDIRECTS(ID_REDIRECT INT PRIMARY KEY AUTO_INCREMENT, URL VARCHAR(45) NOT NULL, R_COUNT INT NOT NULL);
INSERT INTO REDIRECTS (URL, R_COUNT) VALUES('vk.com', 10);
INSERT INTO REDIRECTS (URL, R_COUNT) VALUES('google.com', 20);
INSERT INTO REDIRECTS (URL, R_COUNT) VALUES('facebook.com', 30);
SELECT * FROM REDIRECTS;